### DISCUSSION TITLE
请问一下，这里的缩进目前没有更好的解决方法吗，我尝试过blockquote里也加入border-left并在blockquote前加入两个缩进，但是缩进好像只加在了引言部分。

### DISCUSSION THREAD

**Discussion by miao010101** [Keldos-Li/typora-latex-theme#176] [Q&A] [answered]
```
/* 一个>的引言仅为两字符缩进，使用>>的引言为传统引言样式，具有左竖线、左缩进 */
blockquote {
  font-style: normal;
  font-family: var(--quote-font), var(--base-Latin-font), var(--base-Chinese-font), -apple-system, serif;
  font-size: var(--quote-font-size);
  padding-left: 2em;
  padding-right: 2em;
  margin-left: 0;
}

blockquote blockquote {
  border-left: 4px solid hsl(0, 0%, 70%);
  padding-left: calc(2ch - 4px);
  padding-right: 0;
  margin-left: -4px;
  border-radius: 0;
}
```

**Comment by RalXYZ** [comment]
@miao010101 
请问您的需求是什么？
比如，您想要实现的排版是什么样的，当下的排版又是什么样的，可以提供一下对比图吗？

**Reply by miao010101** [reply]
具体情况如图示
![未命名_页面_1](https://github.com/user-attachments/assets/030602a2-fba7-4cd2-8d60-8ab14ee0cca8)
目前我已经尝试过对代码进行初步的修改，我的逻辑是一二级引言样式修改为相同样式，并在一级样式前或者是整个引言块前加入 2 个字符的缩进。但是由于代码水平有限，出现的情况是只有引言内容前加上了 2 个字符的缩进，但是竖线位置依旧不对。
为了展示缩进，使用 PS 加入了缩进示意线

**Reply by RalXYZ** [reply]
@miao010101 感谢您的耐心解释。

我们内部讨论了一下，认识到：
1. 当下，各级 blockquote 的样式存在不一致的情况：一级 blockquote 左侧没有粗竖线，其他等级的 blockquote 左侧有粗竖线。
2. 在将样式修改得一致的过程中，可能存在元素不对齐的情况。

考虑到：

1. 用户对 blockquote 渲染结果的诉求不同。有些用户认为，latex 风格的主题， blockquote  应该“干干净净的” 没有粗竖线；又有的用户倾向于保留粗竖线。

我们提出的解决方案是：

1. 设置一个“功能开关”（或者代码块，总之 要方便用快速启用/禁用）：默认关闭所有 blockquote 左侧的粗竖线；如果用户更倾向于启用粗竖线，用户可以快速在源代码中启用这一功能。简单来说：要么全都没有粗竖线，要么全都有粗竖线。
2. 在修改的过程中，重点留意：将各元素对齐。

基于以上内容，我后面会创建一个 issue。 **我们目前还没有对相关的 CSS 进行深入分析，所以短时间内无法直接回答您的问题。** 但，以上功能，我们后面会进行开发。

不知道我们是否准确理解了您的诉求。如果我们理解的不准确，欢迎您进行补充；如果您愿意为这一功能贡献代码，您后面可以向我们的项目提相关的 pr。

**Reply by RalXYZ** [reply]
已创建 issue https://github.com/Keldos-Li/typora-latex-theme/issues/177

**Reply by miao010101** [reply, marked as answer]
@RalXYZ emmm，可能是我的表述使问题复杂化了，我的需求简单而言就是如何使用“>“”来完成目前“>>”（两个“>”）所展示的格式。目前我的解决办法是将整个blockquote向右偏移，目前已经达到了想要的效果。

```css
/* 通过对源代码修改，使一个>即可展示引言的传统样式，具有左竖线、左缩进 */
blockquote {
  font-style: normal;
  font-family: var(--quote-font), var(--base-Latin-font), var(--base-Chinese-font), -apple-system, serif;
  font-size: var(--quote-font-size);
  padding-left: calc(2ch - 4px);
  padding-right: 2em;
  /* 使用偏移来展示左缩进 */
  margin-left: calc(4ch - 4px);
  /* 加入左竖线 */
  border-left: 4px solid hsl(0, 0%, 70%);
}

blockquote blockquote {
  border-left: 4px solid hsl(0, 0%, 70%);
  padding-left: calc(2ch - 4px);
  padding-right: 0;
  margin-left: -4px;
  border-radius: 0;
}
```

同时我也明白了Keldos老师的意思，因为我仔细翻阅了部分有关引言格式的博客，二级引言这一格式可能并不规范，确切来讲这很可能是我的老师或者是我自己的一个错误认知（因为我和我的老师讨论过引言部分还能不能再引用另外一个引言，当时我和我老师的意见是应该可以），但现在我认识到Keldos老师的本意可能就是如您所说“用户对 blockquote 渲染结果的诉求不同。有些用户认为，latex 风格的主题， blockquote 应该“干干净净的” 没有粗竖线；又有的用户倾向于保留粗竖线。”因此对于后续的修改部分，我的建议是可以将我上述代码的以下部分

```css
/* 通过对源代码修改，使一个>即可展示引言的传统样式，具有左竖线、左缩进 */
blockquote {
  font-style: normal;
  font-family: var(--quote-font), var(--base-Latin-font), var(--base-Chinese-font), -apple-system, serif;
  font-size: var(--quote-font-size);
  padding-left: calc(2ch - 4px);
  padding-right: 2em;
  /* 使用偏移来展示左缩进 */
  margin-left: calc(4ch - 4px);
  /* 加入左竖线 */
  border-left: 4px solid hsl(0, 0%, 70%);
}
```

作为一个备选方案，共大家选择。同时我也对目前版本代码进行了修改，加入了两端对齐功能，目前感觉比较实用，修改部分如下：

```css
#write p {
  text-align: justify; /* 使正文两端对齐 */
  text-justify: inter-word; /* 只在单词之间添加空隙，避免字符之间出现空隙 */
  line-height: var(--base-line-height);
}
```

Keldos老师在此处的text-align为左对齐，如果直接改为justify后会因为中英混合而出现一些排版错误，故新加入了“text-justify: inter-word; /* 只在单词之间添加空隙，避免字符之间出现空隙 */”

![c7305afae1caea6396a399f748e2edb](https://github.com/user-attachments/assets/cea8bfb3-0c9c-4edb-947e-0f850596ce4e)
