### ISSUE TITLE
关于代码块的背景颜色

### ISSUE THREAD

**Issue by YANthinkn** [Keldos-Li/typora-latex-theme#103]
### 需求描述
大佬你好！这个仿LaTex的主题很好用，但是美中不足的一点就是代码块的背景颜色是白色的，有时候很难区分边界。因此，想询问一下如何修改css文件中的相关代码，使其与默认主题的代码块背景颜色相同（#f8f8f8）？

**Comment by YANthinkn** [comment]
不好意思，提交的时候网卡了...出现了两个issue

**Comment by Keldos-Li** [comment]
我把前一个重复的 issue 删掉了哈。你需要的核心代码大概是这样吧，我从 GitHub 主题的 CSS 文件上复制过来了。你把这段代码粘贴进 CSS 文件中即可。

```css
.md-fences {
  border: 1px solid #e7eaed;
  background-color: #f8f8f8; 
  border-radius: 3px;
}
```
