### ISSUE TITLE
去掉二级标题的序号

### ISSUE THREAD

**Issue by HaHaRen6** [Keldos-Li/typora-latex-theme#119]
如何去掉二级标题（h2）的序号，但保持h3,h4等序号不变

```
#write h2:before {
  counter-increment: h2;
  content: counter(h2);
  margin-right: 1.2em;
}
```

我尝试将这里第三行注释掉，但是h3就从0.1开始了

**Comment by Keldos-Li** [comment]
```css
#write h2:before {
  counter-increment: h2;
  content: counter(h2);
  /* margin-right: 1.2em; */
  visibility: hidden;
  position: absolute;
}
```
