### ISSUE TITLE
标题编号怎么取消？

### ISSUE THREAD

**Issue by liyangzbx** [Keldos-Li/typora-latex-theme#140]
原文的已有编号，这个主题会重新编号，每个标题就有两个编号了。
![Snipaste_2024-07-10_10-28-31](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/fde6445f-5d5e-4d46-b0dd-173a5252546d)

**Comment by Keldos-Li** [comment]
可以删掉原文已有的编号（？
标题编号是这个主题重要的一部分哇

**Comment by edr1412** [comment]
如果完全不想要编号，可以取消吗
有时不写论文也爱用这个主题

**Comment by Keldos-Li** [comment]
如果一定要取消，css文件里找个地方加上：
```css
#write h1:before, #write h2:before, #write h3:before, #write h4:before, #write h5:before, #write h6:before {
  content: "" !important;
  margin-right: 0 !important;
}
```
把编号覆盖掉吧
