### ISSUE TITLE
代码块行号的字体未被替换为设置内代码字体

### ISSUE THREAD

**Issue by Zxis233** [Keldos-Li/typora-latex-theme#154]
这个是否有办法替换？

**Comment by Keldos-Li** [comment]
可以的，在CSS中加入

```CSS
.CodeMirror-sizer {
  font-family: var(--code-font), var(--ui-font), monospace;
}
```
即可。

我去把仓库的代码也更新一下。
