### ISSUE TITLE
导出pdf时出现行距变化，导致部分行重叠

### ISSUE THREAD

**Issue by chenyuan0001** [Keldos-Li/typora-latex-theme#171]
### 操作系统

win11

### 问题描述

导出后的格式保持与typora里渲染的不一致，行距被修改，导致重叠

### 预期行为

导出后的格式保持与typora里渲染的一致

### 屏幕截图

![图片](https://github.com/user-attachments/assets/2ebbb5cd-5c7c-4639-b39e-84375959fb62)

**Comment by Keldos-Li** [comment]
你好，我使用目前的0.3.1版本导出并没有发现该问题，能否提供一下你修改的主题文件或者md源文件？

**Comment by Keldos-Li** [comment]
Hi，用邮箱回复的 github issue thread 我们无法收到附件，你可以发送附件到我的这个邮箱：[hi@keldos.me](mailto:hi@keldos.me) , 谢谢~

**Comment by Keldos-Li** [comment]
附件已收到。

我在mac上导出并没有问题：
<img width="1765" alt="image" src="https://github.com/user-attachments/assets/378e9267-0f5f-4e84-860b-f70c5876a5bb">

也许可以下载新的release文件替换之前的主题样式重新试试？或者重启一下typora或者电脑什么的，说不定是它抽风了。

**Comment by zerc7** [comment]
我在 Windows 11 上遇到了同样的问题，发现在 0.3.1 上导出 PDF/HTML 格式，文档中的无序列表和有序列表出现重叠错位的情况，而在 0.3.0 及之前的版本上正常。
对比两份的 latex.css 文件发现只要将 0.3.1 版本的 第 387~401 行代码

```css
#write ol,
#write ul {
  padding-inline-start: 2em;
}

#write li {
  position: relative;
}
#write li + li,
#write ul + ol > li,
#write ol + ul > li,
#write li > ul > li,
#write li > ol > li {
  margin-top: -0.8em;
}
```

替换成 0.3.0 的相应代码

```css
li {
  position: relative;
}

ol, ul {
  padding-inline-start: 2em;
}
```

就可以正常渲染。
