### ISSUE TITLE
统一各级 blockquote 的样式

### ISSUE THREAD

**Issue by RalXYZ** [Keldos-Li/typora-latex-theme#177]
### Discussed in https://github.com/Keldos-Li/typora-latex-theme/discussions/176

1. 当下，各级 blockquote 的样式存在不一致的情况：一级 blockquote 左侧没有粗竖线，其他等级的 blockquote 左侧有粗竖线。
2. 在将样式修改得一致的过程中，可能存在元素不对齐的情况。

考虑到：

1. 用户对 blockquote 渲染结果的诉求不同。有些用户认为，latex 风格的主题， blockquote  应该“干干净净的” 没有粗竖线；又有的用户倾向于保留粗竖线。

我们提出的解决方案是：

1. 设置一个“功能开关”（或者代码块，总之 要方便用快速启用/禁用）：默认关闭所有 blockquote 左侧的粗竖线；如果用户更倾向于启用粗竖线，用户可以快速在源代码中启用这一功能。简单来说：要么全都没有粗竖线，要么全都有粗竖线。
2. 在修改的过程中，重点留意：将各元素对齐。

**Comment by miao010101** [comment]
如果一级 blockquote 左侧需要有粗竖线可以将原有部分修改为

```css
/* 通过对源代码修改，使一个>即可展示引言的传统样式，具有左竖线、左缩进 */
blockquote {
  font-style: normal;
  font-family: var(--quote-font), var(--base-Latin-font), var(--base-Chinese-font), -apple-system, serif;
  font-size: var(--quote-font-size);
  padding-left: calc(2ch - 4px);
  padding-right: 2em;
  /* 使用偏移来展示左缩进 */
  margin-left: calc(4ch - 4px);
  /* 加入左竖线 */
  border-left: 4px solid hsl(0, 0%, 70%);
}
```
