### ISSUE TITLE
黑色模式适配的两个小问题

### ISSUE THREAD

**Issue by doubleZ0108** [Keldos-Li/typora-latex-theme#29]
童鞋有两个地方的深色适配有点点问题哦 希望有机会的话修改一下～～

1. 一些quick open的小框（🌰e.g. 插入代码框弹出的语言候选框）
部分这些地方的选择器，和Typora官方Night主题的样式⬇️

```css
.auto-suggest-container {
  border: 0px;
  background-color: #525C65;
}

#typora-quick-open {
  background-color: #525C65;
}

#typora-quick-open input{
  background-color: #525C65;
  border: 0;
  border-bottom: 1px solid grey;
}
```

2. 插入图片之后弹出的小框也有深色的适配问题呢
同样附上Typora官方Night主题的选择器和样式⬇️

```css
.context-menu,
#spell-check-panel,
#footer-word-count-info {
    background-color: #42464A;
}
```
