### ISSUE TITLE
Text with hyperlink looks identical with plain text in exported PDF

### ISSUE THREAD

**Issue by Co1lin** [Keldos-Li/typora-latex-theme#41]
Text with hyperlink like [this](http://domain/path) looks the same as a plain one in exported PDF. However, text with hyperlink can be rendered blue with underlines in the editor. Other Typora themes like "Github" don't have this issue.

**Comment by Keldos-Li** [comment]
emm，这是故意这么做的，理论上是一个feature \_(:з」∠)\_  。
当时想的是导出时格式优先适用于打印论文，所以故意把超链接在导出时改回黑色(继承）了。 这个是在[这个commit](https://github.com/Keldos-Li/typora-latex-theme/commit/bb4ba0f3a36a84f8d2c698e7c721651266b7eadc)里新增的。

如果不想要这样，可以去掉scss里这里：
```scss
@media print {
  #write {
    padding: 0 !important;
  }
  #write a {                ////
    color: inherit;         ////
    text-decoration: none   ////
  }                         ////
  @page {
    margin: 1.8cm 2cm 1.2cm 2cm !important; /* 页边距 */
  }
}
```
带`////`标记的那几行。

嘶……我个人觉得最终输出PDF的话，超链接还是用满足交论文的正文颜色比较好？emm有别的看法，或许我应该多加一点注释为用户提供选项？
