### ISSUE TITLE
Format bug for quote in tables

### ISSUE THREAD

**Issue by zhzh2001** [Keldos-Li/typora-latex-theme#53]
### 操作系统
Windows 10 Home China 21H1
Typora v0.11.18

### 问题描述
~~又来乱提 issue 了。~~

表格中的行内代码样式和表格外不同，即不是蓝色，没有框线。在编辑模式下和导出 PDF、HTML 均存在这个问题，其他主题没有本问题。

### 复现方法
以下代码可以复现：
```markdown
This is `code text`. 

| column 1 | column 2 |
| -------- | -------- |
| `code 1` | normal |
```

### 预期行为
表格中的行内代码样式应该与表格外一致。

### 屏幕截图
![image](https://user-images.githubusercontent.com/24852958/143685975-9159b4cc-e83b-44aa-9c28-3e84a77022d3.png)

### 附加内容
将 `code` 限定去掉可以解决这个问题，我不是很确定为什么要加限定。

```css
/* 行内代码 */
/*p code,
li code {*/
code {
  color: #3c70c6;
  background-color: #fefefe;
  /*...*/
}
```

![image](https://user-images.githubusercontent.com/24852958/143685953-44ed0d15-534e-444d-b412-9b094cb50dd9.png)

**Comment by Keldos-Li** [comment]
可能是当时没想到还会有代码块出现在表格里叭_(:з」∠)_ 一开始限定是因为大 code block 的样式代码还没写，会有影响……

虽然我个人觉得表格里的话这个蓝框框就不合适了，我可能只会改个字体，像下面这样：
```css
/* 行内代码 */
code {
  font-family: var(--code-font), var(--ui-font), monospace; }
p code,
li code {
  color: #3c70c6;
  background-color: #fefefe;
  box-shadow: 0 0 1px 1px #c8d3df;
  /* ... */ }
```
🤔（毕竟真实的LaTeX代码块是没有框的）

**Comment by RalXYZ** [comment]
![image](https://user-images.githubusercontent.com/19510622/143689310-0c4cba75-8c89-4af5-b37e-69d57bdbdb4c.png)
![image](https://user-images.githubusercontent.com/19510622/143689319-738e5c0e-49b3-438a-92ce-bdf0bc2243b4.png)

@Keldos-Li 
顺便，在标题里的行内引用会使得字体变为无衬线的...

**Comment by Keldos-Li** [comment]
```css
/* 行内代码 */
code {
  font-family: var(--code-font), var(--ui-font), monospace;
}
h1 code, h2 code, h3 code, h4 code, h5 code, h6 code,
p code,
li code {
  color: #3c70c6;
  background-color: #fefefe;
  box-shadow: 0 0 1px 1px #c8d3df;
  /* 阴影 */
  font-family: var(--code-font), var(--ui-font), monospace;
  box-sizing: border-box;
  border-right: 0px;
  margin: 0 2px 0 2px;
  padding: 0 2px 0 2px;
  border-radius: 2px 2px 2px 2px;
  /* 圆角 */ }
```

这样🤔？

**Comment by Keldos-Li** [comment]
```css
/* 行内代码 */
code {
  font-family: var(--code-font), var(--ui-font), monospace;
}
h1 code, h2 code, h3 code, h4 code, h5 code, h6 code,
p code,
li code {
  color: #3c70c6;
  background-color: #fefefe;
  box-shadow: 0 0 1px 1px #c8d3df;
  /* 阴影 */
  font-family: var(--code-font), var(--ui-font), monospace;
  box-sizing: border-box;
  border-right: 0px;
  margin: 0 2px 0 2px;
  padding: 0 2px 0 2px;
  border-radius: 2px 2px 2px 2px;
  /* 圆角 */ }
```

这样🤔？
