### ISSUE TITLE
标题字重的bug

### ISSUE THREAD

**Issue by jz8-armohb** [Keldos-Li/typora-latex-theme#61]
您好！

英文标题的字重似乎有问题，以`essay-template.md`为例，各级别标题的英文部分看起来都是常规体（中文部分正常），但是`essay-template.pdf`中的字重就是正确的。

后来我在css中修改了标题的字重，以`#write h3#`为例：

```css
#write h3 {
  font-family: var(--heading-Latin-font), var(--h3-Chinese-font), sans-serif;
  font-size: var(--h3-font-size);
  font-weight: bold;
  line-height: var(--h3-font-size);
}
```

加入了`font-weight`，这样英文字体看起来正常了，但是中文字体又被额外加粗了。

请问该如何修改？
