### ISSUE TITLE
分散选择器到不同 scss 文件的尝试

### ISSUE THREAD

**Issue by NaOHCC** [Keldos-Li/typora-latex-theme#73]
起因是我对照着我学校的论文格式，修改相关设置，但这个项目暂时没有标题、正文的段前段后距。我去源文件的一些选择器添加 margin 属性。虽然有相当多的设置集中在 :root 选择器，而且注释齐全，但这个过程还是挺麻烦的，主要是各种选择器都集中在一个文件，上下翻来翻去费时间= =。这两天我通过 scss 的 @import 把 sass 样式分散到多个文件，并做了些[微小的尝试](https://github.com/NaOHCC/typora-latex-theme-cumt)，这样开发者添加功能时挺方便的。

不过我的仓库对这个项目进行了许多破坏性的改动，比如把暗黑模式整个删了；之前我用正则把 css 的自定义变量（--.*）替换成 scss 的变量（$.*），但添加回来都不算困难。

另外有些字体回退设计的有点不合理，比如：
```css
.CodeMirror-code pre {
        font-family: var(--code-font), var(--ui-font), monospace;
    }
```
但不妨就在`--code-font`中考虑回退，取消选择器中的回退 ，这样更方便拿到 css 的同学修改。
```css
    --code-font: var("Latin Modern Mono", "Latin Modern Mono 10", "Courier New",--ui-font), monospace;
/* ... */
.CodeMirror-code pre {
        font-family: var(--code-font);
    }
```
我的想法是，通过分散文件，所有的变量都在 _setting.scss 中设置（包括回退机制），小文件中只引用变量就行（现在还有不小差距），开发者和普通同学修改 css 都更方便，添加更细粒度的控制（emmm 感觉一通操作下来，typora 被玩成 word 了？但 css 确实有这个能力XD）
