### ISSUE TITLE
行间公式字体

### ISSUE THREAD

**Issue by yy98c0** [Keldos-Li/typora-latex-theme#85]
行间公式字体有点小 css找了半天 不知道哪个是改字体大小的

**Comment by Keldos-Li** [comment]
我记得之前develop分支里推过这个commit，但好像被回滚了orz
在css里面找个地方加入这段：
```css
.MathJax {
    font-size: 15pt; /* 你要的字体大小*/
}
```
